-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbCommitResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ApbCommitResp = ApbCommitResp
  { success :: !PB.Bool
  , commitTime :: !(PB.Maybe PB.ByteString)
  , errorcode :: !(PB.Maybe PB.Word32)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbCommitResp where
  defaultVal = ApbCommitResp
    { success = PB.defaultVal
    , commitTime = PB.defaultVal
    , errorcode = PB.defaultVal
    }

instance PB.Mergeable ApbCommitResp where
  merge a b = ApbCommitResp
    { success = PB.merge (success a) (success b)
    , commitTime = PB.merge (commitTime a) (commitTime b)
    , errorcode = PB.merge (errorcode a) (errorcode b)
    }

instance PB.Required ApbCommitResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbCommitResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{success = PB.merge (success self) v}) <$> PB.getBool
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{commitTime = PB.merge (commitTime self) v}) <$> PB.getBytesOpt
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{errorcode = PB.merge (errorcode self) v}) <$> PB.getUInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBool (PB.WireTag 1 PB.VarInt) (success self)
    PB.putBytesOpt (PB.WireTag 2 PB.LenDelim) (commitTime self)
    PB.putUInt32Opt (PB.WireTag 3 PB.VarInt) (errorcode self)


