-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbCounterUpdate where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbCounterUpdate = ApbCounterUpdate
  { inc :: PB.Maybe PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbCounterUpdate where
  defaultVal = ApbCounterUpdate
    { inc = PB.defaultVal
    }

instance PB.Mergeable ApbCounterUpdate where
  merge a b = ApbCounterUpdate
    { inc = PB.merge (inc a) (inc b)
    }

instance PB.Required ApbCounterUpdate where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbCounterUpdate where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{inc = PB.merge (inc self) v}) <$> PB.getSInt64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt64Opt (PB.WireTag 1 PB.VarInt) (inc self)


