-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbCommitTransaction where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbCommitTransaction = ApbCommitTransaction
  { transactionDescriptor :: PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbCommitTransaction where
  defaultVal = ApbCommitTransaction
    { transactionDescriptor = PB.defaultVal
    }

instance PB.Mergeable ApbCommitTransaction where
  merge a b = ApbCommitTransaction
    { transactionDescriptor = PB.merge (transactionDescriptor a) (transactionDescriptor b)
    }

instance PB.Required ApbCommitTransaction where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim]

instance PB.WireMessage ApbCommitTransaction where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transactionDescriptor = PB.merge (transactionDescriptor self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytes (PB.WireTag 1 PB.LenDelim) (transactionDescriptor self)


