-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetIntegerResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetIntegerResp = ApbGetIntegerResp
  { value :: PB.Int64
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetIntegerResp where
  defaultVal = ApbGetIntegerResp
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbGetIntegerResp where
  merge a b = ApbGetIntegerResp
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbGetIntegerResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbGetIntegerResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSInt64
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt64 (PB.WireTag 1 PB.VarInt) (value self)


