-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetMVRegResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetMVRegResp = ApbGetMVRegResp
  { values :: PB.Seq PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetMVRegResp where
  defaultVal = ApbGetMVRegResp
    { values = PB.defaultVal
    }

instance PB.Mergeable ApbGetMVRegResp where
  merge a b = ApbGetMVRegResp
    { values = PB.merge (values a) (values b)
    }

instance PB.Required ApbGetMVRegResp where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbGetMVRegResp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{values = PB.append (values self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytesList (PB.WireTag 1 PB.LenDelim) (values self)


