-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetFlagResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetFlagResp = ApbGetFlagResp
  { value :: PB.Bool
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetFlagResp where
  defaultVal = ApbGetFlagResp
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbGetFlagResp where
  merge a b = ApbGetFlagResp
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbGetFlagResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbGetFlagResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getBool
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBool (PB.WireTag 1 PB.VarInt) (value self)


