-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetSetResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetSetResp = ApbGetSetResp
  { value :: PB.Seq PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetSetResp where
  defaultVal = ApbGetSetResp
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbGetSetResp where
  merge a b = ApbGetSetResp
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbGetSetResp where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbGetSetResp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.append (value self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytesList (PB.WireTag 1 PB.LenDelim) (value self)


