-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetCounterResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetCounterResp = ApbGetCounterResp
  { value :: PB.Int32
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetCounterResp where
  defaultVal = ApbGetCounterResp
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbGetCounterResp where
  merge a b = ApbGetCounterResp
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbGetCounterResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbGetCounterResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getSInt32
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt32 (PB.WireTag 1 PB.VarInt) (value self)


