-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetMapResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbMapEntry

newtype ApbGetMapResp = ApbGetMapResp
  { entries :: PB.Seq Antidote.ApbMapEntry.ApbMapEntry
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetMapResp where
  defaultVal = ApbGetMapResp
    { entries = PB.defaultVal
    }

instance PB.Mergeable ApbGetMapResp where
  merge a b = ApbGetMapResp
    { entries = PB.merge (entries a) (entries b)
    }

instance PB.Required ApbGetMapResp where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbGetMapResp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{entries = PB.append (entries self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessageList (PB.WireTag 1 PB.LenDelim) (entries self)


