-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbGetRegResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbGetRegResp = ApbGetRegResp
  { value :: PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbGetRegResp where
  defaultVal = ApbGetRegResp
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbGetRegResp where
  merge a b = ApbGetRegResp
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbGetRegResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim]

instance PB.WireMessage ApbGetRegResp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytes (PB.WireTag 1 PB.LenDelim) (value self)


