-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbIntegerUpdate where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ApbIntegerUpdate = ApbIntegerUpdate
  { inc :: !(PB.Maybe PB.Int64)
  , set :: !(PB.Maybe PB.Int64)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbIntegerUpdate where
  defaultVal = ApbIntegerUpdate
    { inc = PB.defaultVal
    , set = PB.defaultVal
    }

instance PB.Mergeable ApbIntegerUpdate where
  merge a b = ApbIntegerUpdate
    { inc = PB.merge (inc a) (inc b)
    , set = PB.merge (set a) (set b)
    }

instance PB.Required ApbIntegerUpdate where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbIntegerUpdate where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{inc = PB.merge (inc self) v}) <$> PB.getSInt64Opt
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{set = PB.merge (set self) v}) <$> PB.getSInt64Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putSInt64Opt (PB.WireTag 1 PB.VarInt) (inc self)
    PB.putSInt64Opt (PB.WireTag 2 PB.VarInt) (set self)


