-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbMapEntry where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbMapKey
import qualified Antidote.ApbReadObjectResp

data ApbMapEntry = ApbMapEntry
  { key :: !Antidote.ApbMapKey.ApbMapKey
  , value :: !Antidote.ApbReadObjectResp.ApbReadObjectResp
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbMapEntry where
  defaultVal = ApbMapEntry
    { key = PB.defaultVal
    , value = PB.defaultVal
    }

instance PB.Mergeable ApbMapEntry where
  merge a b = ApbMapEntry
    { key = PB.merge (key a) (key b)
    , value = PB.merge (value a) (value b)
    }

instance PB.Required ApbMapEntry where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim, PB.WireTag 2 PB.LenDelim]

instance PB.WireMessage ApbMapEntry where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{key = PB.merge (key self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessage (PB.WireTag 1 PB.LenDelim) (key self)
    PB.putMessage (PB.WireTag 2 PB.LenDelim) (value self)


