-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbMapNestedUpdate where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbMapKey
import qualified Antidote.ApbUpdateOperation

data ApbMapNestedUpdate = ApbMapNestedUpdate
  { key :: !Antidote.ApbMapKey.ApbMapKey
  , update :: !Antidote.ApbUpdateOperation.ApbUpdateOperation
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbMapNestedUpdate where
  defaultVal = ApbMapNestedUpdate
    { key = PB.defaultVal
    , update = PB.defaultVal
    }

instance PB.Mergeable ApbMapNestedUpdate where
  merge a b = ApbMapNestedUpdate
    { key = PB.merge (key a) (key b)
    , update = PB.merge (update a) (update b)
    }

instance PB.Required ApbMapNestedUpdate where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim, PB.WireTag 2 PB.LenDelim]

instance PB.WireMessage ApbMapNestedUpdate where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{key = PB.merge (key self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{update = PB.merge (update self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessage (PB.WireTag 1 PB.LenDelim) (key self)
    PB.putMessage (PB.WireTag 2 PB.LenDelim) (update self)


