-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbOperationResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ApbOperationResp = ApbOperationResp
  { success :: !PB.Bool
  , errorcode :: !(PB.Maybe PB.Word32)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbOperationResp where
  defaultVal = ApbOperationResp
    { success = PB.defaultVal
    , errorcode = PB.defaultVal
    }

instance PB.Mergeable ApbOperationResp where
  merge a b = ApbOperationResp
    { success = PB.merge (success a) (success b)
    , errorcode = PB.merge (errorcode a) (errorcode b)
    }

instance PB.Required ApbOperationResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbOperationResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{success = PB.merge (success self) v}) <$> PB.getBool
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{errorcode = PB.merge (errorcode self) v}) <$> PB.getUInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBool (PB.WireTag 1 PB.VarInt) (success self)
    PB.putUInt32Opt (PB.WireTag 2 PB.VarInt) (errorcode self)


