-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbReadObjectsResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbReadObjectResp

data ApbReadObjectsResp = ApbReadObjectsResp
  { success :: !PB.Bool
  , objects :: !(PB.Seq Antidote.ApbReadObjectResp.ApbReadObjectResp)
  , errorcode :: !(PB.Maybe PB.Word32)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbReadObjectsResp where
  defaultVal = ApbReadObjectsResp
    { success = PB.defaultVal
    , objects = PB.defaultVal
    , errorcode = PB.defaultVal
    }

instance PB.Mergeable ApbReadObjectsResp where
  merge a b = ApbReadObjectsResp
    { success = PB.merge (success a) (success b)
    , objects = PB.merge (objects a) (objects b)
    , errorcode = PB.merge (errorcode a) (errorcode b)
    }

instance PB.Required ApbReadObjectsResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbReadObjectsResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{success = PB.merge (success self) v}) <$> PB.getBool
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{objects = PB.append (objects self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{errorcode = PB.merge (errorcode self) v}) <$> PB.getUInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBool (PB.WireTag 1 PB.VarInt) (success self)
    PB.putMessageList (PB.WireTag 2 PB.LenDelim) (objects self)
    PB.putUInt32Opt (PB.WireTag 3 PB.VarInt) (errorcode self)


