-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbRegUpdate where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

newtype ApbRegUpdate = ApbRegUpdate
  { value :: PB.ByteString
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbRegUpdate where
  defaultVal = ApbRegUpdate
    { value = PB.defaultVal
    }

instance PB.Mergeable ApbRegUpdate where
  merge a b = ApbRegUpdate
    { value = PB.merge (value a) (value b)
    }

instance PB.Required ApbRegUpdate where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim]

instance PB.WireMessage ApbRegUpdate where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{value = PB.merge (value self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytes (PB.WireTag 1 PB.LenDelim) (value self)


