-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbStartTransactionResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ApbStartTransactionResp = ApbStartTransactionResp
  { success :: !PB.Bool
  , transactionDescriptor :: !(PB.Maybe PB.ByteString)
  , errorcode :: !(PB.Maybe PB.Word32)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbStartTransactionResp where
  defaultVal = ApbStartTransactionResp
    { success = PB.defaultVal
    , transactionDescriptor = PB.defaultVal
    , errorcode = PB.defaultVal
    }

instance PB.Mergeable ApbStartTransactionResp where
  merge a b = ApbStartTransactionResp
    { success = PB.merge (success a) (success b)
    , transactionDescriptor = PB.merge (transactionDescriptor a) (transactionDescriptor b)
    , errorcode = PB.merge (errorcode a) (errorcode b)
    }

instance PB.Required ApbStartTransactionResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbStartTransactionResp where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{success = PB.merge (success self) v}) <$> PB.getBool
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{transactionDescriptor = PB.merge (transactionDescriptor self) v}) <$> PB.getBytesOpt
  fieldToValue (PB.WireTag 3 PB.VarInt) self = (\v -> self{errorcode = PB.merge (errorcode self) v}) <$> PB.getUInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBool (PB.WireTag 1 PB.VarInt) (success self)
    PB.putBytesOpt (PB.WireTag 2 PB.LenDelim) (transactionDescriptor self)
    PB.putUInt32Opt (PB.WireTag 3 PB.VarInt) (errorcode self)


