-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbStartTransaction where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbTxnProperties

data ApbStartTransaction = ApbStartTransaction
  { timestamp :: !(PB.Maybe PB.ByteString)
  , properties :: !(PB.Maybe Antidote.ApbTxnProperties.ApbTxnProperties)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbStartTransaction where
  defaultVal = ApbStartTransaction
    { timestamp = PB.defaultVal
    , properties = PB.defaultVal
    }

instance PB.Mergeable ApbStartTransaction where
  merge a b = ApbStartTransaction
    { timestamp = PB.merge (timestamp a) (timestamp b)
    , properties = PB.merge (properties a) (properties b)
    }

instance PB.Required ApbStartTransaction where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbStartTransaction where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{timestamp = PB.merge (timestamp self) v}) <$> PB.getBytesOpt
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{properties = PB.merge (properties self) v}) <$> PB.getMessageOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putBytesOpt (PB.WireTag 1 PB.LenDelim) (timestamp self)
    PB.putMessageOpt (PB.WireTag 2 PB.LenDelim) (properties self)


