-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbStaticReadObjectsResp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbReadObjectsResp
import qualified Antidote.ApbCommitResp

data ApbStaticReadObjectsResp = ApbStaticReadObjectsResp
  { objects :: !Antidote.ApbReadObjectsResp.ApbReadObjectsResp
  , committime :: !Antidote.ApbCommitResp.ApbCommitResp
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbStaticReadObjectsResp where
  defaultVal = ApbStaticReadObjectsResp
    { objects = PB.defaultVal
    , committime = PB.defaultVal
    }

instance PB.Mergeable ApbStaticReadObjectsResp where
  merge a b = ApbStaticReadObjectsResp
    { objects = PB.merge (objects a) (objects b)
    , committime = PB.merge (committime a) (committime b)
    }

instance PB.Required ApbStaticReadObjectsResp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim, PB.WireTag 2 PB.LenDelim]

instance PB.WireMessage ApbStaticReadObjectsResp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{objects = PB.merge (objects self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{committime = PB.merge (committime self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessage (PB.WireTag 1 PB.LenDelim) (objects self)
    PB.putMessage (PB.WireTag 2 PB.LenDelim) (committime self)


