-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbSetUpdate where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.SetOpType

data ApbSetUpdate = ApbSetUpdate
  { optype :: !Antidote.SetOpType.SetOpType
  , adds :: !(PB.Seq PB.ByteString)
  , rems :: !(PB.Seq PB.ByteString)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbSetUpdate where
  defaultVal = ApbSetUpdate
    { optype = PB.defaultVal
    , adds = PB.defaultVal
    , rems = PB.defaultVal
    }

instance PB.Mergeable ApbSetUpdate where
  merge a b = ApbSetUpdate
    { optype = PB.merge (optype a) (optype b)
    , adds = PB.merge (adds a) (adds b)
    , rems = PB.merge (rems a) (rems b)
    }

instance PB.Required ApbSetUpdate where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.VarInt]

instance PB.WireMessage ApbSetUpdate where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{optype = PB.merge (optype self) v}) <$> PB.getEnum
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{adds = PB.append (adds self) v}) <$> PB.getBytes
  fieldToValue (PB.WireTag 3 PB.LenDelim) self = (\v -> self{rems = PB.append (rems self) v}) <$> PB.getBytes
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putEnum (PB.WireTag 1 PB.VarInt) (optype self)
    PB.putBytesList (PB.WireTag 2 PB.LenDelim) (adds self)
    PB.putBytesList (PB.WireTag 3 PB.LenDelim) (rems self)


