-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbStaticUpdateObjects where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbStartTransaction
import qualified Antidote.ApbUpdateOp

data ApbStaticUpdateObjects = ApbStaticUpdateObjects
  { transaction :: !Antidote.ApbStartTransaction.ApbStartTransaction
  , updates :: !(PB.Seq Antidote.ApbUpdateOp.ApbUpdateOp)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbStaticUpdateObjects where
  defaultVal = ApbStaticUpdateObjects
    { transaction = PB.defaultVal
    , updates = PB.defaultVal
    }

instance PB.Mergeable ApbStaticUpdateObjects where
  merge a b = ApbStaticUpdateObjects
    { transaction = PB.merge (transaction a) (transaction b)
    , updates = PB.merge (updates a) (updates b)
    }

instance PB.Required ApbStaticUpdateObjects where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim]

instance PB.WireMessage ApbStaticUpdateObjects where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{transaction = PB.merge (transaction self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{updates = PB.append (updates self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessage (PB.WireTag 1 PB.LenDelim) (transaction self)
    PB.putMessageList (PB.WireTag 2 PB.LenDelim) (updates self)


