-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbTxnProperties where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB

data ApbTxnProperties = ApbTxnProperties
  { readWrite :: !(PB.Maybe PB.Word32)
  , redBlue :: !(PB.Maybe PB.Word32)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbTxnProperties where
  defaultVal = ApbTxnProperties
    { readWrite = PB.defaultVal
    , redBlue = PB.defaultVal
    }

instance PB.Mergeable ApbTxnProperties where
  merge a b = ApbTxnProperties
    { readWrite = PB.merge (readWrite a) (readWrite b)
    , redBlue = PB.merge (redBlue a) (redBlue b)
    }

instance PB.Required ApbTxnProperties where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbTxnProperties where
  fieldToValue (PB.WireTag 1 PB.VarInt) self = (\v -> self{readWrite = PB.merge (readWrite self) v}) <$> PB.getUInt32Opt
  fieldToValue (PB.WireTag 2 PB.VarInt) self = (\v -> self{redBlue = PB.merge (redBlue self) v}) <$> PB.getUInt32Opt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putUInt32Opt (PB.WireTag 1 PB.VarInt) (readWrite self)
    PB.putUInt32Opt (PB.WireTag 2 PB.VarInt) (redBlue self)


