-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbUpdateOperation where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbCounterUpdate
import qualified Antidote.ApbSetUpdate
import qualified Antidote.ApbRegUpdate
import qualified Antidote.ApbIntegerUpdate
-- import qualified Antidote.ApbMapUpdate
import qualified Antidote.ApbCrdtReset
import qualified Antidote.ApbFlagUpdate

data ApbUpdateOperation = ApbUpdateOperation
  { counterop :: !(PB.Maybe Antidote.ApbCounterUpdate.ApbCounterUpdate)
  , setop :: !(PB.Maybe Antidote.ApbSetUpdate.ApbSetUpdate)
  , regop :: !(PB.Maybe Antidote.ApbRegUpdate.ApbRegUpdate)
  , integerop :: !(PB.Maybe Antidote.ApbIntegerUpdate.ApbIntegerUpdate)
  , mapop :: !(PB.Maybe Antidote.ApbCounterUpdate.ApbCounterUpdate) --Antidote.ApbMapUpdate.ApbMapUpdate)
  , resetop :: !(PB.Maybe Antidote.ApbCrdtReset.ApbCrdtReset)
  , flagop :: !(PB.Maybe Antidote.ApbFlagUpdate.ApbFlagUpdate)
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbUpdateOperation where
  defaultVal = ApbUpdateOperation
    { counterop = PB.defaultVal
    , setop = PB.defaultVal
    , regop = PB.defaultVal
    , integerop = PB.defaultVal
    , mapop = PB.defaultVal
    , resetop = PB.defaultVal
    , flagop = PB.defaultVal
    }

instance PB.Mergeable ApbUpdateOperation where
  merge a b = ApbUpdateOperation
    { counterop = PB.merge (counterop a) (counterop b)
    , setop = PB.merge (setop a) (setop b)
    , regop = PB.merge (regop a) (regop b)
    , integerop = PB.merge (integerop a) (integerop b)
    , mapop = PB.merge (mapop a) (mapop b)
    , resetop = PB.merge (resetop a) (resetop b)
    , flagop = PB.merge (flagop a) (flagop b)
    }

instance PB.Required ApbUpdateOperation where
  reqTags _ = PB.fromList []

instance PB.WireMessage ApbUpdateOperation where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{counterop = PB.merge (counterop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{setop = PB.merge (setop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 3 PB.LenDelim) self = (\v -> self{regop = PB.merge (regop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 4 PB.LenDelim) self = (\v -> self{integerop = PB.merge (integerop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 5 PB.LenDelim) self = (\v -> self{mapop = PB.merge (mapop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 6 PB.LenDelim) self = (\v -> self{resetop = PB.merge (resetop self) v}) <$> PB.getMessageOpt
  fieldToValue (PB.WireTag 7 PB.LenDelim) self = (\v -> self{flagop = PB.merge (flagop self) v}) <$> PB.getMessageOpt
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessageOpt (PB.WireTag 1 PB.LenDelim) (counterop self)
    PB.putMessageOpt (PB.WireTag 2 PB.LenDelim) (setop self)
    PB.putMessageOpt (PB.WireTag 3 PB.LenDelim) (regop self)
    PB.putMessageOpt (PB.WireTag 4 PB.LenDelim) (integerop self)
    PB.putMessageOpt (PB.WireTag 5 PB.LenDelim) (mapop self)
    PB.putMessageOpt (PB.WireTag 6 PB.LenDelim) (resetop self)
    PB.putMessageOpt (PB.WireTag 7 PB.LenDelim) (flagop self)
