-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.ApbUpdateOp where

import Control.Applicative ((<$>))
import Prelude ()
import qualified Data.ProtoBufInt as PB
import qualified Antidote.ApbBoundObject
import qualified Antidote.ApbUpdateOperation

data ApbUpdateOp = ApbUpdateOp
  { boundobject :: !Antidote.ApbBoundObject.ApbBoundObject
  , operation :: !Antidote.ApbUpdateOperation.ApbUpdateOperation
  } deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default ApbUpdateOp where
  defaultVal = ApbUpdateOp
    { boundobject = PB.defaultVal
    , operation = PB.defaultVal
    }

instance PB.Mergeable ApbUpdateOp where
  merge a b = ApbUpdateOp
    { boundobject = PB.merge (boundobject a) (boundobject b)
    , operation = PB.merge (operation a) (operation b)
    }

instance PB.Required ApbUpdateOp where
  reqTags _ = PB.fromList [PB.WireTag 1 PB.LenDelim, PB.WireTag 2 PB.LenDelim]

instance PB.WireMessage ApbUpdateOp where
  fieldToValue (PB.WireTag 1 PB.LenDelim) self = (\v -> self{boundobject = PB.merge (boundobject self) v}) <$> PB.getMessage
  fieldToValue (PB.WireTag 2 PB.LenDelim) self = (\v -> self{operation = PB.merge (operation self) v}) <$> PB.getMessage
  fieldToValue tag self = PB.getUnknown tag self

  messageToFields self = do
    PB.putMessage (PB.WireTag 1 PB.LenDelim) (boundobject self)
    PB.putMessage (PB.WireTag 2 PB.LenDelim) (operation self)


