-- Generated by protobuf-simple. DO NOT EDIT!
module Antidote.SetOpType where

import Prelude ()
import qualified Data.ProtoBufInt as PB

data SetOpType = Add | Remove
  deriving (PB.Show, PB.Eq, PB.Ord)

instance PB.Default SetOpType where
  defaultVal = Add

instance PB.Mergeable SetOpType where

instance PB.WireEnum SetOpType where
  intToEnum 1 = Add
  intToEnum 2 = Remove
  intToEnum _ = PB.defaultVal

  enumToInt Add = 1
  enumToInt Remove = 2


